apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 133480914580.dkr.ecr.us-east-1.amazonaws.com/shopping-site-computers:0d2296f06d99e6b0a3f539ec828239b4d3df884d
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: computers-service
  labels:
    app: computers
spec:
  type: ClusterIP
  selector:
    app: computers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
