apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 133480914580.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlegrocery:5af2849d44273b49c8b0506bd0df7570386ec28c
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: googlegrocery-service
  labels:
    app: googlegrocery
spec:
  type: ClusterIP
  selector:
    app: googlegrocery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
